// web/src/pages/LoginPage.tsx
import { useCallback, useEffect, useState } from 'react'
import { InputField } from '@/components/ui/input-field'
import { Button } from '@/components/ui/button'
import { useAuthStore } from '@/stores/auth'
import { useLoginLockout } from '@/hooks/useLoginLockout'
import { getSetupStatus } from '@/api/endpoints/setup'
import { getErrorMessage } from '@/utils/errors'
import { MIN_PASSWORD_LENGTH } from '@/utils/constants'

type Mode = 'loading' | 'login' | 'setup'

export default function LoginPage() {
  const [mode, setMode] = useState<Mode>('loading')
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [submitting, setSubmitting] = useState(false)
  const [minPasswordLength, setMinPasswordLength] = useState(MIN_PASSWORD_LENGTH)

  const login = useAuthStore((s) => s.login)
  const setup = useAuthStore((s) => s.setup)
  const { locked, checkAndClearLockout, recordFailure, reset } = useLoginLockout()

  // Detect first-run vs normal login on mount.
  useEffect(() => {
    let cancelled = false
    getSetupStatus()
      .then((status) => {
        if (cancelled) return
        if (status.needs_admin) {
          setMode('setup')
          setMinPasswordLength(status.min_password_length ?? MIN_PASSWORD_LENGTH)
        } else {
          setMode('login')
        }
      })
      .catch(() => {
        if (!cancelled) setMode('login')
      })
    return () => { cancelled = true }
  }, [])

  const handleLogin = useCallback(async () => {
    setError(null)
    if (!username.trim()) {
      setError('Username is required')
      return
    }
    if (!password) {
      setError('Password is required')
      return
    }
    if (checkAndClearLockout()) return

    setSubmitting(true)
    try {
      await login(username, password)
      reset()
    } catch (err) {
      const lockoutMsg = recordFailure(err)
      setError(lockoutMsg ?? getErrorMessage(err))
    } finally {
      setSubmitting(false)
    }
  }, [username, password, login, checkAndClearLockout, recordFailure, reset])

  const handleSetup = useCallback(async () => {
    setError(null)
    if (!username.trim()) {
      setError('Username is required')
      return
    }
    if (password.length < minPasswordLength) {
      setError(`Password must be at least ${minPasswordLength} characters`)
      return
    }
    if (password !== confirmPassword) {
      setError('Passwords do not match')
      return
    }

    setSubmitting(true)
    try {
      await setup(username, password)
    } catch (err) {
      setError(getErrorMessage(err))
    } finally {
      setSubmitting(false)
    }
  }, [username, password, confirmPassword, minPasswordLength, setup])

  const handleSubmit = useCallback(
    (e: React.FormEvent) => {
      e.preventDefault()
      if (mode === 'loading') return
      if (mode === 'setup') {
        void handleSetup()
      } else {
        void handleLogin()
      }
    },
    [mode, handleSetup, handleLogin],
  )

  const disabled = submitting || locked

  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <div className="w-full max-w-sm">
        <form
          onSubmit={handleSubmit}
          className="rounded-lg border border-border bg-card p-8 space-y-6"
        >
          {/* Wordmark */}
          <p className="text-center font-sans text-2xl font-bold text-accent">
            SynthOrg
          </p>

          {mode === 'loading' ? (
            <p className="text-center text-sm text-muted-foreground">
              Checking setup status...
            </p>
          ) : (
            <>
              {/* Heading */}
              <div className="space-y-1">
                <h1 className="text-lg font-semibold text-foreground">
                  {mode === 'setup' ? 'Create Admin Account' : 'Sign In'}
                </h1>
                {mode === 'setup' && (
                  <p className="text-sm text-muted-foreground">
                    Set up your administrator account to get started.
                  </p>
                )}
              </div>

              {/* Fields */}
              <div className="space-y-4">
                <InputField
                  label="Username"
                  type="text"
                  value={username}
                  onChange={(e) => setUsername(e.currentTarget.value)}
                  disabled={disabled}
                  autoComplete="username"
                  autoFocus
                />

                <InputField
                  label="Password"
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.currentTarget.value)}
                  disabled={disabled}
                  autoComplete={mode === 'setup' ? 'new-password' : 'current-password'}
                  hint={mode === 'setup' ? `At least ${minPasswordLength} characters` : undefined}
                />

                {mode === 'setup' && (
                  <InputField
                    label="Confirm Password"
                    type="password"
                    value={confirmPassword}
                    onChange={(e) => setConfirmPassword(e.currentTarget.value)}
                    disabled={disabled}
                    autoComplete="new-password"
                  />
                )}
              </div>

              {/* Error */}
              {error && (
                <div
                  role="alert"
                  className="rounded-md border border-danger/30 bg-danger/5 px-3 py-2 text-sm text-danger"
                >
                  {error}
                </div>
              )}

              {/* Lockout warning */}
              {locked && !error && (
                <div
                  role="alert"
                  className="rounded-md border border-warning/30 bg-warning/5 px-3 py-2 text-sm text-warning"
                >
                  Too many failed attempts. Please wait before trying again.
                </div>
              )}

              {/* Submit */}
              <Button type="submit" className="w-full" disabled={disabled}>
                {submitting
                  ? (mode === 'setup' ? 'Creating Account...' : 'Signing In...')
                  : (mode === 'setup' ? 'Create Account' : 'Sign In')}
              </Button>
            </>
          )}
        </form>
      </div>
    </div>
  )
}

// web/src/views/LoginPage.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import InputText from 'primevue/inputtext'
import Password from 'primevue/password'
import Button from 'primevue/button'
import { useToast } from 'primevue/usetoast'
import { useAuthStore } from '@/stores/auth'
import { getErrorMessage } from '@/utils/errors'
import { MIN_PASSWORD_LENGTH } from '@/utils/constants'
import { useLoginLockout } from '@/composables/useLoginLockout'

const router = useRouter()
const auth = useAuthStore()
const toast = useToast()
const { locked, checkAndClearLockout, recordFailure, reset } = useLoginLockout()

const username = ref('')
const password = ref('')
const error = ref<string | null>(null)

async function handleLogin() {
  if (checkAndClearLockout()) {
    error.value = 'Too many failed attempts. Please wait before trying again.'
    return
  }
  error.value = null
  try {
    await auth.login(username.value, password.value)
    reset()
    if (auth.mustChangePassword) {
      toast.add({ severity: 'warn', summary: 'Password change required', life: 5000 })
    }
    router.push('/')
  } catch (err) {
    const lockoutMsg = recordFailure(err)
    if (lockoutMsg) {
      error.value = lockoutMsg
      return
    }
    error.value = getErrorMessage(err)
  }
}

function goToSetup() {
  router.push('/setup')
}
</script>

<template>
  <div class="flex min-h-screen items-center justify-center bg-slate-950 p-4">
    <div class="w-full max-w-sm">
      <!-- Logo -->
      <div class="mb-8 text-center">
        <div class="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-brand-600 text-xl font-bold text-white">
          S
        </div>
        <h1 class="text-2xl font-semibold text-slate-100">
          SynthOrg
        </h1>
        <p class="mt-1 text-sm text-slate-400">
          Sign in to your dashboard
        </p>
      </div>

      <!-- Form -->
      <form
        class="space-y-4"
        @submit.prevent="handleLogin"
      >
        <div>
          <label
            for="username"
            class="mb-1 block text-sm text-slate-300"
          >Username</label>
          <InputText
            id="username"
            v-model="username"
            class="w-full"
            placeholder="Enter username"
            autocomplete="username"
            :aria-describedby="error ? 'login-error' : undefined"
          />
        </div>
        <div>
          <label
            for="password"
            class="mb-1 block text-sm text-slate-300"
          >Password</label>
          <Password
            v-model="password"
            input-id="password"
            :toggle-mask="true"
            :feedback="false"
            fluid
            :placeholder="`Password (min ${MIN_PASSWORD_LENGTH} chars)`"
            :input-props="{
              autocomplete: 'current-password',
              'aria-describedby': error ? 'login-error' : undefined,
            }"
          />
        </div>

        <div
          v-if="error"
          id="login-error"
          role="alert"
          class="rounded bg-red-500/10 p-3 text-sm text-red-400"
        >
          {{ error }}
        </div>

        <Button
          type="submit"
          label="Sign In"
          icon="pi pi-sign-in"
          class="w-full"
          :loading="auth.loading"
          :disabled="!username || !password || locked"
        />
      </form>

      <div class="mt-6 text-center">
        <button
          class="text-sm text-slate-500 hover:text-brand-400"
          @click="goToSetup"
        >
          First time? Set up admin account
        </button>
      </div>
    </div>
  </div>
</template>
