// web/src/pages/tasks/TaskDetailPanel.tsx
import { useCallback, useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { X, Loader2, Calendar, GitBranch, User, Tag, Layers } from 'lucide-react'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { InlineEdit } from '@/components/ui/inline-edit'
import { ConfirmDialog } from '@/components/ui/confirm-dialog'
import { TaskStatusIndicator } from '@/components/ui/task-status-indicator'
import { PriorityBadge } from '@/components/ui/task-status-indicator'
import { Avatar } from '@/components/ui/avatar'
import { springDefault, overlayBackdrop } from '@/lib/motion'
import { getTaskStatusLabel, getTaskTypeLabel, getAvailableTransitions, getPriorityLabel } from '@/utils/tasks'
import { formatDate, formatCurrency } from '@/utils/format'
import { useToastStore } from '@/stores/toast'
import { getErrorMessage } from '@/utils/errors'
import type { Task, Priority, UpdateTaskRequest, TransitionTaskRequest, CancelTaskRequest, TaskStatus } from '@/api/types'

export interface TaskDetailPanelProps {
  task: Task
  onClose: () => void
  onUpdate: (taskId: string, data: UpdateTaskRequest) => Promise<void>
  onTransition: (taskId: string, data: TransitionTaskRequest) => Promise<void>
  onCancel: (taskId: string, data: CancelTaskRequest) => Promise<void>
  onDelete: (taskId: string) => Promise<void>
  loading?: boolean
}

const PANEL_VARIANTS = {
  initial: { x: '100%', opacity: 0 },
  animate: { x: 0, opacity: 1, transition: springDefault },
  exit: { x: '100%', opacity: 0, transition: { duration: 0.15, ease: 'easeIn' as const } },
}

const PRIORITIES: Priority[] = ['critical', 'high', 'medium', 'low']

export function TaskDetailPanel({
  task,
  onClose,
  onUpdate,
  onTransition,
  onCancel,
  onDelete,
  loading,
}: TaskDetailPanelProps) {
  const [cancelOpen, setCancelOpen] = useState(false)
  const [deleteOpen, setDeleteOpen] = useState(false)
  const [cancelReason, setCancelReason] = useState('')
  const [transitioning, setTransitioning] = useState<TaskStatus | null>(null)

  const availableTransitions = getAvailableTransitions(task.status)

  // Close panel on Escape key (skip when a dialog is open)
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        if (document.querySelector('[role="alertdialog"], [role="dialog"][aria-modal="true"]')) return
        onClose()
      }
    }
    document.addEventListener('keydown', handleKeyDown)
    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [onClose])

  const handleTransition = useCallback(async (targetStatus: TaskStatus) => {
    setTransitioning(targetStatus)
    try {
      await onTransition(task.id, { target_status: targetStatus, expected_version: task.version })
    } catch {
      useToastStore.getState().add({ variant: 'error', title: 'Transition failed' })
    } finally {
      setTransitioning(null)
    }
  }, [task.id, task.version, onTransition])

  const handleCancel = useCallback(async () => {
    if (!cancelReason.trim()) {
      useToastStore.getState().add({ variant: 'error', title: 'Please provide a cancellation reason' })
      return
    }
    try {
      await onCancel(task.id, { reason: cancelReason.trim() })
      setCancelOpen(false)
      setCancelReason('')
    } catch {
      useToastStore.getState().add({ variant: 'error', title: 'Failed to cancel task' })
    }
  }, [task.id, cancelReason, onCancel])

  const handleDelete = useCallback(async () => {
    try {
      await onDelete(task.id)
      setDeleteOpen(false)
      onClose()
    } catch {
      useToastStore.getState().add({ variant: 'error', title: 'Failed to delete task' })
    }
  }, [task.id, onDelete, onClose])

  return (
    <>
      {/* Backdrop */}
      <motion.div
        className="fixed inset-0 z-40 bg-background/60 backdrop-blur-sm"
        variants={overlayBackdrop}
        initial="initial"
        animate="animate"
        exit="exit"
        onClick={onClose}
      />

      {/* Panel */}
      <motion.aside
        className="fixed top-0 right-0 z-50 flex h-full w-full max-w-lg flex-col border-l border-border bg-base shadow-lg"
        variants={PANEL_VARIANTS}
        initial="initial"
        animate="animate"
        exit="exit"
        role="dialog"
        aria-label={`Task detail: ${task.title}`}
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-border px-6 py-4">
          <div className="flex items-center gap-2">
            <TaskStatusIndicator status={task.status} label />
          </div>
          <Button variant="ghost" size="icon" onClick={onClose} aria-label="Close panel">
            <X className="size-4" />
          </Button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-6 py-4 space-y-6">
          {loading && (
            <div className="flex items-center justify-center py-8">
              <Loader2 className="size-6 animate-spin text-text-muted" />
            </div>
          )}

          {!loading && (
            <>
              {/* Title */}
              <InlineEdit
                value={task.title}
                onSave={async (value) => {
                  try {
                    await onUpdate(task.id, { title: value, expected_version: task.version })
                  } catch (err) {
                    useToastStore.getState().add({ variant: 'error', title: 'Failed to save title', description: getErrorMessage(err) })
                    throw err
                  }
                }}
                validate={(v) => v.trim().length === 0 ? 'Title is required' : null}
                className="text-lg font-semibold"
              />

              {/* Description */}
              <div>
                <label className="text-[11px] font-semibold uppercase tracking-wider text-text-muted">Description</label>
                <InlineEdit
                  value={task.description}
                  onSave={async (value) => {
                    try {
                      await onUpdate(task.id, { description: value, expected_version: task.version })
                    } catch (err) {
                      useToastStore.getState().add({ variant: 'error', title: 'Failed to save description', description: getErrorMessage(err) })
                      throw err
                    }
                  }}
                  className="mt-1 text-sm text-text-secondary"
                />
              </div>

              {/* Priority */}
              <div>
                <label className="text-[11px] font-semibold uppercase tracking-wider text-text-muted">Priority</label>
                <div className="mt-1 flex items-center gap-2">
                  <PriorityBadge priority={task.priority} />
                  <select
                    value={task.priority}
                    onChange={async (e) => {
                      try {
                        await onUpdate(task.id, { priority: e.target.value as Priority, expected_version: task.version })
                      } catch (err) {
                        useToastStore.getState().add({ variant: 'error', title: 'Failed to update priority', description: getErrorMessage(err) })
                      }
                    }}
                    className="h-7 rounded border border-border bg-surface px-1.5 text-xs text-foreground focus:outline-none focus:ring-2 focus:ring-accent"
                    aria-label="Change priority"
                  >
                    {PRIORITIES.map((p) => (
                      <option key={p} value={p}>{getPriorityLabel(p)}</option>
                    ))}
                  </select>
                </div>
              </div>

              {/* Assignee */}
              <div>
                <div className="flex items-center gap-2">
                  <User className="size-4 text-text-muted" />
                  <span className="text-[11px] font-semibold uppercase tracking-wider text-text-muted">Assignee</span>
                </div>
                <div className="mt-1 flex items-center gap-2">
                  {task.assigned_to && <Avatar name={task.assigned_to} size="sm" />}
                  <InlineEdit
                    value={task.assigned_to ?? ''}
                    onSave={async (value) => {
                      try {
                        await onUpdate(task.id, { assigned_to: value.trim() || undefined, expected_version: task.version })
                      } catch (err) {
                        useToastStore.getState().add({ variant: 'error', title: 'Failed to update assignee', description: getErrorMessage(err) })
                        throw err
                      }
                    }}
                    className="text-sm"
                    placeholder="Unassigned"
                  />
                </div>
              </div>

              {/* Metadata grid */}
              <div className="grid grid-cols-2 gap-4 rounded-lg border border-border p-3">
                <MetaField icon={Tag} label="Type" value={getTaskTypeLabel(task.type)} />
                <MetaField icon={Layers} label="Complexity" value={task.estimated_complexity} />
                <MetaField icon={Calendar} label="Created" value={formatDate(task.created_at)} />
                <MetaField icon={Calendar} label="Updated" value={formatDate(task.updated_at)} />
                {task.deadline && (
                  <MetaField icon={Calendar} label="Deadline" value={formatDate(task.deadline)} />
                )}
                {task.cost_usd != null && (
                  <MetaField icon={Tag} label="Cost" value={formatCurrency(task.cost_usd, 'USD')} />
                )}
              </div>

              {/* Dependencies */}
              {task.dependencies.length > 0 && (
                <div>
                  <div className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-wider text-text-muted">
                    <GitBranch className="size-3.5" />
                    Dependencies ({task.dependencies.length})
                  </div>
                  <ul className="mt-1.5 space-y-1">
                    {task.dependencies.map((depId) => (
                      <li key={depId} className="rounded border border-border px-2 py-1 font-mono text-xs text-text-secondary">
                        {depId}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Acceptance criteria */}
              {task.acceptance_criteria.length > 0 && (
                <div>
                  <span className="text-[11px] font-semibold uppercase tracking-wider text-text-muted">
                    Acceptance Criteria
                  </span>
                  <ul className="mt-1.5 space-y-1">
                    {task.acceptance_criteria.map((criterion) => (
                      <li key={criterion.description} className="flex items-start gap-2 text-xs text-text-secondary">
                        <span className={cn('mt-0.5 size-3.5 shrink-0 rounded border', criterion.met ? 'border-success bg-success/20' : 'border-border')} />
                        {criterion.description}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Transitions */}
              {availableTransitions.length > 0 && (
                <div>
                  <span className="text-[11px] font-semibold uppercase tracking-wider text-text-muted">
                    Transitions
                  </span>
                  <div className="mt-1.5 flex flex-wrap gap-2">
                    {availableTransitions.map((targetStatus) => (
                      <Button
                        key={targetStatus}
                        size="sm"
                        variant="outline"
                        disabled={transitioning !== null}
                        onClick={() => handleTransition(targetStatus)}
                      >
                        {transitioning === targetStatus && <Loader2 className="mr-1 size-3 animate-spin" />}
                        {getTaskStatusLabel(targetStatus)}
                      </Button>
                    ))}
                  </div>
                </div>
              )}
            </>
          )}
        </div>

        {/* Footer actions */}
        <div className="flex items-center justify-end gap-2 border-t border-border px-6 py-3">
          {task.status !== 'cancelled' && task.status !== 'completed' && (
            <Button variant="outline" size="sm" onClick={() => setCancelOpen(true)}>
              Cancel Task
            </Button>
          )}
          <Button variant="destructive" size="sm" onClick={() => setDeleteOpen(true)}>
            Delete
          </Button>
        </div>
      </motion.aside>

      {/* Cancel dialog */}
      <ConfirmDialog
        open={cancelOpen}
        onOpenChange={(open) => { setCancelOpen(open); if (!open) setCancelReason('') }}
        title="Cancel Task"
        description="Are you sure? Please provide a reason for cancellation."
        confirmLabel="Cancel Task"
        variant="destructive"
        onConfirm={handleCancel}
      >
        <textarea
          value={cancelReason}
          onChange={(e) => setCancelReason(e.target.value)}
          placeholder="Reason for cancellation..."
          className="mt-2 w-full rounded-md border border-border bg-surface px-2 py-1.5 text-sm text-foreground outline-none resize-y focus:ring-2 focus:ring-accent min-h-[60px]"
          aria-label="Cancellation reason"
        />
      </ConfirmDialog>

      {/* Delete dialog */}
      <ConfirmDialog
        open={deleteOpen}
        onOpenChange={setDeleteOpen}
        title="Delete Task"
        description="This action cannot be undone. The task and all associated data will be permanently deleted."
        confirmLabel="Delete"
        variant="destructive"
        onConfirm={handleDelete}
      />
    </>
  )
}

function MetaField({ icon: Icon, label, value }: { icon: typeof Tag; label: string; value: string }) {
  return (
    <div className="flex items-start gap-2">
      <Icon className="mt-0.5 size-3.5 text-text-muted" aria-hidden="true" />
      <div>
        <span className="block text-[10px] text-text-muted">{label}</span>
        <span className="block text-xs capitalize text-foreground">{value}</span>
      </div>
    </div>
  )
}

// web/src/components/tasks/TaskDetailPanel.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import Sidebar from 'primevue/sidebar'
import Button from 'primevue/button'
import InputText from 'primevue/inputtext'
import Textarea from 'primevue/textarea'
import Dropdown from 'primevue/dropdown'
import StatusBadge from '@/components/common/StatusBadge.vue'
import type { Task, Priority, TaskStatus } from '@/api/types'
import { VALID_TRANSITIONS, TERMINAL_STATUSES } from '@/utils/constants'
import { formatDate, formatCurrency } from '@/utils/format'
import { useAuth } from '@/composables/useAuth'

const props = defineProps<{
  task: Task | null
  visible: boolean
}>()

const emit = defineEmits<{
  'update:visible': [value: boolean]
  save: [taskId: string, data: { title?: string; description?: string; priority?: Priority }]
  transition: [taskId: string, targetStatus: TaskStatus, version: number]
  cancel: [taskId: string, reason: string]
}>()

const { canWrite } = useAuth()
const editing = ref(false)
const editTitle = ref('')
const editDescription = ref('')
const editPriority = ref<Priority>('medium')
const cancelReason = ref('')
const showCancel = ref(false)

const priorityOptions = [
  { label: 'Critical', value: 'critical' },
  { label: 'High', value: 'high' },
  { label: 'Medium', value: 'medium' },
  { label: 'Low', value: 'low' },
]

watch(
  () => props.task,
  (task) => {
    if (task) {
      editTitle.value = task.title
      editDescription.value = task.description
      editPriority.value = task.priority
      editing.value = false
      showCancel.value = false
      cancelReason.value = ''
    }
  },
  { immediate: true },
)

function getTransitions(): readonly TaskStatus[] {
  if (!props.task) return []
  return VALID_TRANSITIONS[props.task.status] ?? []
}

function saveEdit() {
  if (!props.task) return
  emit('save', props.task.id, {
    title: editTitle.value,
    description: editDescription.value,
    priority: editPriority.value,
  })
  editing.value = false
}

function handleTransition(status: TaskStatus) {
  if (!props.task) return
  emit('transition', props.task.id, status, props.task.version ?? 0)
}

function handleCancel() {
  if (!props.task || !cancelReason.value.trim()) return
  emit('cancel', props.task.id, cancelReason.value)
  showCancel.value = false
}
</script>

<template>
  <Sidebar :visible="visible" position="right" class="w-[480px]" @update:visible="$emit('update:visible', $event)">
    <template #header>
      <span class="text-lg font-semibold text-slate-100">Task Details</span>
    </template>

    <div v-if="task" class="space-y-6">
      <!-- Title & Description -->
      <div v-if="!editing">
        <h2 class="text-lg font-medium text-slate-100">{{ task.title }}</h2>
        <p class="mt-2 text-sm text-slate-400 whitespace-pre-wrap">{{ task.description }}</p>
        <Button
          v-if="canWrite && !TERMINAL_STATUSES.has(task.status)"
          label="Edit"
          icon="pi pi-pencil"
          text
          size="small"
          class="mt-2"
          @click="editing = true"
        />
      </div>
      <div v-else class="space-y-3">
        <InputText v-model="editTitle" class="w-full" />
        <Textarea v-model="editDescription" class="w-full" rows="4" />
        <Dropdown v-model="editPriority" :options="priorityOptions" option-label="label" option-value="value" class="w-full" />
        <div class="flex gap-2">
          <Button label="Save" icon="pi pi-check" size="small" @click="saveEdit" />
          <Button label="Cancel" icon="pi pi-times" text size="small" @click="editing = false" />
        </div>
      </div>

      <!-- Metadata -->
      <div class="grid grid-cols-2 gap-4 rounded-lg border border-slate-800 p-4">
        <div>
          <p class="text-xs text-slate-500">Status</p>
          <StatusBadge :value="task.status" />
        </div>
        <div>
          <p class="text-xs text-slate-500">Priority</p>
          <StatusBadge :value="task.priority" type="priority" />
        </div>
        <div>
          <p class="text-xs text-slate-500">Type</p>
          <p class="text-sm text-slate-300">{{ task.type }}</p>
        </div>
        <div>
          <p class="text-xs text-slate-500">Complexity</p>
          <p class="text-sm text-slate-300">{{ task.estimated_complexity }}</p>
        </div>
        <div>
          <p class="text-xs text-slate-500">Assignee</p>
          <p class="text-sm text-slate-300">{{ task.assigned_to ?? 'Unassigned' }}</p>
        </div>
        <div>
          <p class="text-xs text-slate-500">Project</p>
          <p class="text-sm text-slate-300">{{ task.project }}</p>
        </div>
        <div>
          <p class="text-xs text-slate-500">Budget Limit</p>
          <p class="text-sm text-slate-300">{{ formatCurrency(task.budget_limit) }}</p>
        </div>
        <div>
          <p class="text-xs text-slate-500">Cost</p>
          <p class="text-sm text-slate-300">{{ formatCurrency(task.cost_usd ?? 0) }}</p>
        </div>
        <div>
          <p class="text-xs text-slate-500">Created</p>
          <p class="text-sm text-slate-300">{{ formatDate(task.created_at) }}</p>
        </div>
        <div>
          <p class="text-xs text-slate-500">Updated</p>
          <p class="text-sm text-slate-300">{{ formatDate(task.updated_at) }}</p>
        </div>
      </div>

      <!-- Transitions -->
      <div v-if="canWrite && getTransitions().length > 0">
        <p class="mb-2 text-xs font-medium text-slate-400">Transition To</p>
        <div class="flex flex-wrap gap-2">
          <Button
            v-for="status in getTransitions()"
            :key="status"
            :label="status.replaceAll('_', ' ')"
            size="small"
            outlined
            @click="handleTransition(status)"
          />
        </div>
      </div>

      <!-- Cancel -->
      <div v-if="canWrite && !TERMINAL_STATUSES.has(task.status)">
        <Button
          v-if="!showCancel"
          label="Cancel Task"
          icon="pi pi-times"
          severity="danger"
          text
          size="small"
          @click="showCancel = true"
        />
        <div v-else class="space-y-2">
          <label for="cancel-reason" class="mb-1 block text-xs text-slate-400">Reason for cancellation</label>
          <Textarea id="cancel-reason" v-model="cancelReason" placeholder="Reason for cancellation" class="w-full" rows="2" aria-required="true" />
          <div class="flex gap-2">
            <Button label="Confirm Cancel" severity="danger" size="small" :disabled="!cancelReason.trim()" @click="handleCancel" />
            <Button label="Back" text size="small" @click="showCancel = false" />
          </div>
        </div>
      </div>
    </div>
  </Sidebar>
</template>
