// web/src/components/providers/ProviderCard.vue
<script setup lang="ts">
import { ref } from 'vue'
import Button from 'primevue/button'
import Tag from 'primevue/tag'
import ProviderTestButton from './ProviderTestButton.vue'
import type { ProviderConfig } from '@/api/types'

const props = defineProps<{
  name: string
  config: ProviderConfig
}>()

const emit = defineEmits<{
  edit: [name: string]
  delete: [name: string]
}>()

const confirmingDelete = ref(false)

function handleDelete() {
  if (!confirmingDelete.value) {
    confirmingDelete.value = true
    return
  }
  emit('delete', props.name)
  confirmingDelete.value = false
}

function cancelDelete() {
  confirmingDelete.value = false
}

function authBadgeSeverity(authType: string): 'success' | 'info' | 'warn' | 'secondary' {
  switch (authType) {
    case 'api_key': return 'info'
    case 'oauth': return 'warn'
    case 'custom_header': return 'secondary'
    case 'none': return 'success'
    default: return 'secondary'
  }
}
</script>

<template>
  <div class="rounded-lg border border-slate-700 bg-slate-800/50 p-4 transition-colors hover:border-slate-600">
    <div class="mb-3 flex items-start justify-between">
      <div>
        <h3 class="text-base font-medium text-slate-200">{{ name }}</h3>
        <div class="mt-1 flex items-center gap-2">
          <Tag :value="config.driver" severity="info" class="text-xs" />
          <Tag :value="config.auth_type" :severity="authBadgeSeverity(config.auth_type)" class="text-xs" />
        </div>
      </div>
      <span class="text-xs text-slate-500">{{ config.models.length }} model{{ config.models.length !== 1 ? 's' : '' }}</span>
    </div>

    <div v-if="config.base_url" class="mb-3 truncate text-xs text-slate-400" :title="config.base_url">
      {{ config.base_url }}
    </div>

    <div class="mb-3 flex flex-wrap gap-1">
      <span
        v-for="model in config.models"
        :key="model.id"
        class="rounded bg-slate-700 px-1.5 py-0.5 text-xs text-slate-300"
      >
        {{ model.alias ?? model.id }}
      </span>
    </div>

    <div class="flex items-center gap-2">
      <ProviderTestButton :provider-name="name" />
      <Button
        label="Edit"
        size="small"
        severity="secondary"
        text
        @click="emit('edit', name)"
      />
      <template v-if="!confirmingDelete">
        <Button
          label="Delete"
          size="small"
          severity="danger"
          text
          @click="handleDelete"
        />
      </template>
      <template v-else>
        <Button
          label="Confirm"
          size="small"
          severity="danger"
          @click="handleDelete"
        />
        <Button
          label="Cancel"
          size="small"
          severity="secondary"
          text
          @click="cancelDelete"
        />
      </template>
    </div>
  </div>
</template>

// web/src/pages/providers/ProviderCard.tsx
import { Server } from 'lucide-react'
import { ProviderHealthBadge } from '@/components/ui/provider-health-badge'
import { cn } from '@/lib/utils'
import type { ProviderHealthSummary } from '@/api/types'
import type { ProviderWithName } from '@/utils/providers'

interface ProviderCardProps {
  provider: ProviderWithName
  health: ProviderHealthSummary | null
  className?: string
}

export function ProviderCard({ provider, health, className }: ProviderCardProps) {
  const displayName = provider.name
  const subtitle = provider.litellm_provider ?? provider.driver

  return (
    <div
      className={cn(
        'rounded-lg border border-border bg-card p-card',
        'transition-all duration-200',
        'hover:bg-card-hover hover:-translate-y-px hover:shadow-[0_4px_24px_var(--so-accent-8)]',
        className,
      )}
    >
      {/* Header */}
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2 min-w-0">
          <Server className="size-4 shrink-0 text-text-secondary" />
          <span className="truncate font-mono text-sm text-foreground">
            {displayName}
          </span>
        </div>
        {health && <ProviderHealthBadge status={health.health_status} label />}
      </div>

      {/* Body */}
      <div className="mt-3 flex flex-col gap-1.5">
        <div className="flex items-center gap-2 text-xs text-text-secondary">
          <span className="truncate">{subtitle}</span>
          <span className="text-text-muted">|</span>
          <span>{provider.auth_type.replace('_', ' ')}</span>
        </div>

        {provider.base_url && (
          <span className="truncate font-mono text-xs text-text-muted">
            {provider.base_url}
          </span>
        )}

        <div className="mt-1 flex items-center gap-2">
          <span className="rounded-md bg-bg-surface px-1.5 py-0.5 text-xs font-mono text-text-secondary">
            {provider.models.length} model{provider.models.length !== 1 ? 's' : ''}
          </span>
          {health && health.calls_last_24h > 0 && (
            <span className="text-xs text-text-muted">
              {health.calls_last_24h} calls/24h
            </span>
          )}
        </div>
      </div>
    </div>
  )
}
