// mockups/direction-db/src/components/Sidebar.tsx
import { NavLink } from 'react-router-dom';

interface NavItem {
  path: string;
  label: string;
  icon: React.ReactNode;
}

const navItems: NavItem[] = [
  {
    path: '/db/',
    label: 'Overview',
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <rect x="3" y="3" width="7" height="7" rx="1" />
        <rect x="14" y="3" width="7" height="7" rx="1" />
        <rect x="3" y="14" width="7" height="7" rx="1" />
        <rect x="14" y="14" width="7" height="7" rx="1" />
      </svg>
    ),
  },
  {
    path: '/db/org',
    label: 'Org Chart',
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="4" r="2" />
        <circle cx="5" cy="16" r="2" />
        <circle cx="19" cy="16" r="2" />
        <line x1="12" y1="6" x2="12" y2="11" />
        <line x1="12" y1="11" x2="5" y2="14" />
        <line x1="12" y1="11" x2="19" y2="14" />
      </svg>
    ),
  },
  {
    path: '/db/agent',
    label: 'People',
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="7" r="3" />
        <path d="M5 20c0-3.87 3.13-7 7-7s7 3.13 7 7" />
      </svg>
    ),
  },
];

const bottomItems: NavItem[] = [
  {
    path: '/db/tasks',
    label: 'Tasks',
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <path d="M9 12l2 2 4-4" />
        <rect x="3" y="3" width="18" height="18" rx="2" />
      </svg>
    ),
  },
  {
    path: '/db/money',
    label: 'Money',
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="9" />
        <path d="M12 7v10M9.5 9.5c0-1.38 1.12-2.5 2.5-2.5s2.5 1.12 2.5 2.5c0 2.5-5 2.5-5 5 0 1.38 1.12 2.5 2.5 2.5s2.5-1.12 2.5-2.5" />
      </svg>
    ),
  },
  {
    path: '/db/settings',
    label: 'Settings',
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="3" />
        <path d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42" />
      </svg>
    ),
  },
];

export default function Sidebar() {
  return (
    <nav
      style={{
        width: '48px',
        minHeight: '100vh',
        backgroundColor: '#0f1117',
        borderRight: '1px solid rgba(255,255,255,0.05)',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        paddingTop: '16px',
        paddingBottom: '16px',
        gap: '4px',
        position: 'fixed',
        left: 0,
        top: 0,
        bottom: 0,
        zIndex: 100,
      }}
    >
      {/* Logo mark */}
      <div style={{ marginBottom: '20px', padding: '4px' }}>
        <div
          style={{
            width: '28px',
            height: '28px',
            backgroundColor: '#6366f1',
            borderRadius: '6px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="white">
            <circle cx="5" cy="5" r="3" />
            <circle cx="19" cy="5" r="3" />
            <circle cx="12" cy="19" r="3" />
            <line x1="5" y1="5" x2="12" y2="19" stroke="white" strokeWidth="2" />
            <line x1="19" y1="5" x2="12" y2="19" stroke="white" strokeWidth="2" />
            <line x1="5" y1="5" x2="19" y2="5" stroke="white" strokeWidth="2" />
          </svg>
        </div>
      </div>

      {/* Main nav items */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '2px', width: '100%', alignItems: 'center', flex: 1 }}>
        {navItems.map((item) => (
          <NavLink
            key={item.path}
            to={item.path}
            end={item.path === '/db/'}
            title={item.label}
            style={({ isActive }) => ({
              width: '36px',
              height: '36px',
              borderRadius: '8px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: isActive ? '#6366f1' : 'rgba(255,255,255,0.35)',
              backgroundColor: isActive ? 'rgba(99,102,241,0.12)' : 'transparent',
              textDecoration: 'none',
              position: 'relative',
              transition: 'color 200ms ease, background-color 200ms ease',
            })}
          >
            {item.icon}
          </NavLink>
        ))}
      </div>

      {/* Bottom nav items */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '2px', width: '100%', alignItems: 'center' }}>
        {bottomItems.map((item) => (
          <NavLink
            key={item.path}
            to={item.path}
            title={item.label}
            style={({ isActive }) => ({
              width: '36px',
              height: '36px',
              borderRadius: '8px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: isActive ? '#6366f1' : 'rgba(255,255,255,0.35)',
              backgroundColor: isActive ? 'rgba(99,102,241,0.12)' : 'transparent',
              textDecoration: 'none',
              transition: 'color 200ms ease, background-color 200ms ease',
            })}
          >
            {item.icon}
          </NavLink>
        ))}
      </div>
    </nav>
  );
}

// mockups/direction-bd/src/components/Sidebar.vue
<template>
  <nav class="sidebar" :class="{ expanded }">
    <div class="sidebar-inner">
      <div
        v-for="item in navItems"
        :key="item.path"
        class="nav-item"
        :class="{ active: currentPath === item.path }"
        @click="navigate(item.path)"
        @mouseenter="hoveredItem = item.id"
        @mouseleave="hoveredItem = null"
      >
        <span class="nav-icon" v-html="item.icon"></span>
        <span class="nav-label">{{ item.label }}</span>
        <span v-if="item.badge" class="nav-badge">{{ item.badge }}</span>
      </div>
    </div>
    <button class="sidebar-toggle" @click="expanded = !expanded" :title="expanded ? 'Collapse' : 'Expand'">
      <span>{{ expanded ? '‹' : '›' }}</span>
    </button>
  </nav>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'

const router = useRouter()
const route = useRoute()
const expanded = ref(false)
const hoveredItem = ref<string | null>(null)

const currentPath = computed(() => route.path)

const navItems = [
  { id: 'overview', path: '/', icon: '⬡', label: 'Overview', badge: null },
  { id: 'org', path: '/org', icon: '◎', label: 'Org Chart', badge: null },
  { id: 'tasks', path: '#', icon: '⊞', label: 'Tasks', badge: '5' },
  { id: 'people', path: '/agent', icon: '◈', label: 'People', badge: null },
  { id: 'money', path: '#', icon: '⊕', label: 'Budget', badge: null },
  { id: 'approvals', path: '#', icon: '◻', label: 'Approvals', badge: '2' },
  { id: 'comms', path: '#', icon: '⊂', label: 'Comms', badge: null },
  { id: 'meetings', path: '#', icon: '○', label: 'Meetings', badge: null },
  { id: 'providers', path: '#', icon: '◇', label: 'Providers', badge: null },
  { id: 'settings', path: '#', icon: '⊛', label: 'Settings', badge: null },
]

function navigate(path: string) {
  if (path !== '#') {
    router.push(path)
  }
}
</script>

<style scoped>
.sidebar {
  width: 60px;
  height: 100%;
  background: rgba(8,8,15,0.95);
  border-right: 1px solid rgba(255,255,255,0.06);
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
  transition: width 0.25s cubic-bezier(0.16,1,0.3,1);
  overflow: hidden;
  position: relative;
  z-index: 50;
}

.sidebar.expanded {
  width: 200px;
}

.sidebar-inner {
  flex: 1;
  padding: 12px 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
  overflow: hidden;
}

.nav-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 10px 18px;
  cursor: pointer;
  border-radius: 0;
  transition: background 0.15s ease;
  position: relative;
  white-space: nowrap;
  min-width: 0;
}

.nav-item:hover {
  background: rgba(59,130,246,0.08);
}

.nav-item:hover .nav-icon {
  color: #3b82f6;
  text-shadow: 0 0 12px rgba(59,130,246,0.8);
}

.nav-item.active {
  background: rgba(59,130,246,0.12);
}

.nav-item.active::before {
  content: '';
  position: absolute;
  left: 0;
  top: 4px;
  bottom: 4px;
  width: 2px;
  background: #3b82f6;
  border-radius: 0 2px 2px 0;
  box-shadow: 0 0 8px rgba(59,130,246,0.6);
}

.nav-item.active .nav-icon {
  color: #3b82f6;
  text-shadow: 0 0 12px rgba(59,130,246,0.8);
}

.nav-icon {
  font-size: 18px;
  color: rgba(255,255,255,0.35);
  transition: color 0.15s, text-shadow 0.15s;
  min-width: 24px;
  text-align: center;
  display: flex;
  align-items: center;
  justify-content: center;
}

.nav-label {
  font-size: 13px;
  color: rgba(255,255,255,0.6);
  opacity: 0;
  transition: opacity 0.2s ease;
  flex: 1;
}

.sidebar.expanded .nav-label {
  opacity: 1;
}

.nav-badge {
  font-size: 10px;
  background: rgba(59,130,246,0.25);
  color: #3b82f6;
  border-radius: 10px;
  padding: 1px 6px;
  font-family: 'JetBrains Mono', monospace;
  opacity: 0;
  transition: opacity 0.2s ease;
}

.sidebar.expanded .nav-badge {
  opacity: 1;
}

.sidebar-toggle {
  width: 100%;
  height: 36px;
  background: transparent;
  border: none;
  border-top: 1px solid rgba(255,255,255,0.06);
  color: rgba(255,255,255,0.25);
  cursor: pointer;
  font-size: 16px;
  transition: color 0.15s, background 0.15s;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.sidebar-toggle:hover {
  color: rgba(255,255,255,0.6);
  background: rgba(255,255,255,0.04);
}
</style>
