// web/src/components/layout/Sidebar.vue
<script setup lang="ts">
import { useRouter, useRoute } from 'vue-router'
import { APP_NAME, NAV_ITEMS } from '@/utils/constants'

defineProps<{
  collapsed: boolean
}>()

defineEmits<{
  toggle: []
}>()

const router = useRouter()
const route = useRoute()

function isActive(to: string): boolean {
  if (to === '/') return route.path === '/'
  // Exact match or path segment match to avoid /agent matching /agents
  return route.path === to || route.path.startsWith(to + '/')
}

function navigate(to: string) {
  router.push(to)
}
</script>

<template>
  <aside
    :class="[
      'flex flex-col border-r border-slate-800 bg-slate-950 transition-all duration-200',
      collapsed ? 'w-16' : 'w-60',
    ]"
  >
    <!-- Logo -->
    <div class="flex h-14 items-center gap-2 border-b border-slate-800 px-4">
      <div class="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-600 text-sm font-bold text-white">
        S
      </div>
      <span
        v-if="!collapsed"
        class="text-lg font-semibold text-slate-100"
      >{{ APP_NAME }}</span>
    </div>

    <!-- Navigation -->
    <nav class="flex-1 overflow-y-auto py-2">
      <button
        v-for="item in NAV_ITEMS"
        :key="item.to"
        type="button"
        :class="[
          'flex w-full items-center gap-3 px-4 py-2.5 text-sm transition-colors',
          isActive(item.to)
            ? 'bg-brand-600/10 text-brand-400'
            : 'text-slate-400 hover:bg-slate-800/50 hover:text-slate-200',
        ]"
        :title="collapsed ? item.label : undefined"
        :aria-label="item.label"
        @click="navigate(item.to)"
      >
        <i :class="[item.icon, 'text-base']" />
        <span v-if="!collapsed">{{ item.label }}</span>
      </button>
    </nav>

    <!-- Collapse toggle -->
    <button
      type="button"
      class="flex items-center justify-center border-t border-slate-800 py-3 text-slate-400 hover:text-slate-200"
      :aria-label="collapsed ? 'Expand sidebar' : 'Collapse sidebar'"
      @click="$emit('toggle')"
    >
      <i
        :class="collapsed ? 'pi pi-angle-right' : 'pi pi-angle-left'"
        aria-hidden="true"
      />
    </button>
  </aside>
</template>

// web/src/components/layout/Sidebar.tsx
import { useState } from 'react'
import {
  Bell,
  Command,
  Cpu,
  DollarSign,
  GitBranch,
  KanbanSquare,
  LayoutDashboard,
  LogOut,
  MessageSquare,
  PanelLeftClose,
  PanelLeftOpen,
  Settings,
  ShieldCheck,
  Users,
  Video,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { useAuth } from '@/hooks/useAuth'
import { useAuthStore } from '@/stores/auth'
import { ROUTES } from '@/router/routes'
import { SidebarNavItem } from './SidebarNavItem'

const STORAGE_KEY = 'sidebar_collapsed'

export function Sidebar() {
  const [collapsed, setCollapsed] = useState(
    () => localStorage.getItem(STORAGE_KEY) === 'true',
  )
  const { user } = useAuth()
  const logout = useAuthStore((s) => s.logout)

  function toggleCollapse() {
    setCollapsed((prev) => {
      const next = !prev
      localStorage.setItem(STORAGE_KEY, String(next))
      return next
    })
  }

  return (
    <aside
      className={cn(
        'flex h-full flex-col border-r border-surface-100 bg-surface-50 transition-[width] duration-200',
        collapsed ? 'w-14' : 'w-[220px]',
      )}
    >
      {/* Header */}
      <div className="flex h-14 shrink-0 items-center border-b border-surface-100 px-3">
        {collapsed ? (
          <span className="mx-auto text-lg font-bold text-brand-400">S</span>
        ) : (
          <span className="text-lg font-bold text-brand-400">SynthOrg</span>
        )}
      </div>

      {/* Navigation */}
      <nav className="flex-1 overflow-y-auto px-2 pt-3" aria-label="Main navigation">
        <div className="flex flex-col gap-1">
          <SidebarNavItem
            to={ROUTES.DASHBOARD}
            icon={LayoutDashboard}
            label="Dashboard"
            collapsed={collapsed}
            end
          />
          <SidebarNavItem
            to={ROUTES.ORG}
            icon={GitBranch}
            label="Org Chart"
            collapsed={collapsed}
          />
          <SidebarNavItem
            to={ROUTES.TASKS}
            icon={KanbanSquare}
            label="Task Board"
            collapsed={collapsed}
          />
          <SidebarNavItem
            to={ROUTES.BUDGET}
            icon={DollarSign}
            label="Budget"
            collapsed={collapsed}
          />
          <SidebarNavItem
            to={ROUTES.APPROVALS}
            icon={ShieldCheck}
            label="Approvals"
            collapsed={collapsed}
            badge={0}
          />
        </div>

        {/* Workspace section */}
        <div className="mt-4 border-t border-surface-100 pt-3">
          {!collapsed && (
            <span className="mb-2 block px-3 text-xs font-medium uppercase tracking-wider text-surface-400">
              Workspace
            </span>
          )}
          <div className="flex flex-col gap-1">
            <SidebarNavItem
              to={ROUTES.AGENTS}
              icon={Users}
              label="Agents"
              collapsed={collapsed}
            />
            <SidebarNavItem
              to={ROUTES.MESSAGES}
              icon={MessageSquare}
              label="Messages"
              collapsed={collapsed}
              badge={0}
            />
            <SidebarNavItem
              to={ROUTES.MEETINGS}
              icon={Video}
              label="Meetings"
              collapsed={collapsed}
            />
            <SidebarNavItem
              to={ROUTES.PROVIDERS}
              icon={Cpu}
              label="Providers"
              collapsed={collapsed}
            />
            <SidebarNavItem
              to={ROUTES.SETTINGS}
              icon={Settings}
              label="Settings"
              collapsed={collapsed}
            />
          </div>
        </div>
      </nav>

      {/* Bottom section (non-navigation controls) */}
      <div className="border-t border-surface-100 px-2 py-3">
        <div className="flex flex-col gap-1">
          {/* Collapse toggle */}
          <button
            onClick={toggleCollapse}
            title={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}
            className="flex items-center gap-3 rounded-md px-3 py-2 text-sm text-surface-500 transition-colors hover:bg-surface-100 hover:text-surface-700"
          >
            {collapsed ? (
              <PanelLeftOpen className="mx-auto size-5" aria-hidden="true" />
            ) : (
              <>
                <PanelLeftClose className="size-5 shrink-0" aria-hidden="true" />
                <span>Collapse</span>
              </>
            )}
          </button>

          {/* Notifications placeholder */}
          <button
            title="Notifications"
            aria-label="Notifications"
            className="flex items-center gap-3 rounded-md px-3 py-2 text-sm text-surface-500 transition-colors hover:bg-surface-100 hover:text-surface-700"
          >
            <Bell
              className={cn('size-5 shrink-0', collapsed && 'mx-auto')}
              aria-hidden="true"
            />
            {!collapsed && <span>Notifications</span>}
          </button>

          {/* Cmd+K hint */}
          {!collapsed && (
            <div className="flex items-center gap-3 px-3 py-2 text-xs text-surface-400">
              <Command className="size-4 shrink-0" aria-hidden="true" />
              <span>Cmd+K to search</span>
            </div>
          )}

          {/* Connection status placeholder */}
          <div
            className={cn(
              'flex items-center gap-3 px-3 py-1',
              collapsed && 'justify-center',
            )}
          >
            <span
              className="size-2 rounded-full bg-success-500"
              title="Connected"
              aria-label="Connection status: connected"
            />
            {!collapsed && (
              <span className="text-xs text-surface-400">Connected</span>
            )}
          </div>

          {/* User / logout */}
          {user && (
            <div
              className={cn(
                'flex items-center gap-3 px-3 py-2',
                collapsed && 'justify-center',
              )}
            >
              {!collapsed && (
                <div className="flex-1 truncate">
                  <div className="text-sm font-medium text-surface-700">
                    {user.username}
                  </div>
                  <div className="text-xs text-surface-400">{user.role}</div>
                </div>
              )}
              <button
                onClick={logout}
                title="Logout"
                aria-label="Logout"
                className="rounded-md p-1 text-surface-400 transition-colors hover:bg-surface-100 hover:text-surface-700"
              >
                <LogOut className="size-4" aria-hidden="true" />
              </button>
            </div>
          )}
        </div>
      </div>
    </aside>
  )
}
